config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'products#index'

  devise_for :users
  get '/users/:id', to: "users#show", :as => :user

  post '/users/:id/follow', to: "users#follow", :as => :follow_user
  post '/users/:id/unfollow', to: "users#unfollow", :as => :unfollow_user

  # vist sidekiq if user is admin
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :products do
    resources :comments # 這應該不用這麼多條

    member do
      post :checkout
      get :seller_of
    end
  end

  resources :comments do
    resources :comments # should use only to arrange the routes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validate :not_following_self
  private
    def not_following_self
      if follower_id == followee_id
        errors.add(:follower_id, 'You cannot follow yourself')
      end
    end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail # also can be has_many_attached
  has_many :comments, as: :commentable, dependent: :destroy

  scope :active, -> { where(status: "active") }
  scope :inactive, -> { where(status: "inactive") }

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail # also can be has_many_attached
  has_many :comments, as: :commentable

  scope :active, -> { where(status: "active") }
  scope :inactive, -> { where(status: "inactive") }

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  
  has_many :products, dependent: :destroy

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :followers, through: :following_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    find_commentable
  	@comment = @commentable.comments.new comment_params
    @comment.user = current_user
    session[:return_to] ||= request.referer
    if @comment.save
      redirect_to session.delete(:return_to)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Product.find_by_id(params[:product_id]) if params[:product_id]
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products/comments_controller.rb
class Products::CommentsController < CommentsController

  before_action :set_commentable

  private
  def set_commentable
    @commentable = Product.find(params[:product_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy checkout]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /projects or /projects.json
  def index
    @products = Product.active
  end

  # GET /projects/1 or /projects/1.json
  def show
    @client_token = Braintree::ClientToken.generate
  end

  # GET /projects/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        ExpireProductJob.set(wait_until: @product.expires_at).perform_later(@product)
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def checkout
    if @product
      nonce = params[:payment_method_nonce]

      result = Braintree::Transaction.sale(
        amount: @product.price,
        payment_method_nonce: nonce
      )

      if result
        redirect_to product_path, notice: "Success!"
      else
        # 錯誤處理
      end
    else
      # 錯誤處理
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :user_id, :description, :thumbnail, :current_available_amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def follow
    if @user == current_user
      flash.alert = "You cannot follow yourself"
    else
      @user = User.find(params[:id])
      current_user.followees << @user
    end
  end
  
  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def author_of(resource)
  	user_signed_in? && resource.user_id == current_user.id
  end

  def admin?
  	user_signed_in? && current_user.admin?
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products/comments_helper.rb
module Products::CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comments.html.erb
<p class="font-bold text-lg">Comments</p>
<% commentable.comments.each do |comment| %>
  <div>
    <%= comment.body %>
    <% comment.comments.each do |comment| %>
      <div>
        <%= comment.body %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new], :remote => true do |f| %>
  <div class="">
    <%= f.text_area :body, class: "input input-with-border", placeholder: placeholder, required: true %>
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/comments/_reply.html.erb
<div class="">
  <div class="">
    <%= reply.body %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="">
  <%= form_for [comment, Comment.new] do |f| %>
    <%= f.label 'Reply' %>
    <%= f.text_area :body %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="max-w-lg mx-auto mt-16 text-center">
  <h1 class="mb-4 text-3xl font-black">Welcome to Kickoff Tailwind!</h1>
  <p class="text-lg leading-snug">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased">
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-blue-500 text-blue-100">
    <%= render "shared/flash_notice" %>
    <%= render "shared/header" %>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/products/_active_product.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flex-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <h1 class="text-3xl font-bold leading-none text-gray-800"><%= product.title %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= product.user.name ||=
      product.user.username %></p>
      </div>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="text-xl text-gray-500"><%= number_to_currency(product.price)%></p>
    </div> 

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= product.current_available_amount %> available</p>
    </div>  

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= distance_of_time_in_words_to_now(product.expires_at) %></p>
      <p class="text-sm text-gray-500">to go</p>
    </div>
  </div>

  <div class="flex flex-wrap items-start justify-between mb-6">
    <div class="w-full lg:w-3/5">
    <% if product.thumbnail.present? %>
      <%= image_tag product.thumbnail, class: "rounded" %>
      <%= url_for(product.thumbnail) %>
      <%= link_to product.thumbnail %>

    <% else %>
      <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
        <div class="">
          <p class="text-xs font-bold text-gray-600 uppercase">product</p>
          <h3 class="text-2xl text-black"><%= product.title %></h3>
        </div>
      </div>
    <% end %>
    </div>
    <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
      <p class="text-sm font-semibold text-gray-500 uppercase">Description</p>
      <%= product.description %>
    </div>
  </div>

  <div class="w-full lg:w-3/5 pb-6">
    <p class="font-bold text-lg">Comments</p>
    <% product.comments.each do |comment| %>
      <div class="font-bold">
        <%= comment.body %>
      </div>
      <% comment.comments.each do |comment| %>
        <div class="px-4">
          <%= comment.body %>
        </div>
      <% end %>
      <%= render "comments/form", commentable: comment, placeholder: "Add a reply" %>
    <% end %>
    <br>
    <br>
    <br>
    <%= render "comments/form", commentable: product, placeholder: "Add a comment" %>
  </div>
  

  <%= form_with(model: product, url: checkout_product_path(product), method: :post) do |f| %>
    <div id="payment-form"></div>
    <%= f.submit "pay", class:"btn btn-default btn-danger" %>
  <% end %>

  <script src="https://js.braintreegateway.com/js/braintree-2.32.1.min.js"></script>
  <script>
    var clientToken = "<%= @client_token %>";
    braintree.setup(clientToken, "dropin", {
      container: "payment-form"
    });
  </script>

 <% if admin? || author_of(product) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_product_path(product), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delete', product_path(product), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, multipart: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="p-6 mb-5 text-red-500 bg-white rounded">
      <h2 class="font-bold text-red-500"><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6 text-xl">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6 text-xl">
    <%= form.label :thumbnail, "Product Thumbnail", class: "label" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="mb-6 text-xl">
    <%= form.label :price, class: "label" %>
    <%= form.text_field :price, class: "input" %>
  </div>

  <div class="mb-6 text-xl">
    <%= form.label :available_amount, "Available Amount", class: "label" %>
    <%= form.text_field :current_available_amount, class: "input" %>
  </div>

  <div class="mb-6 text-xl">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input" %>
  </div>

  <div class="mb-6 text-xl">
    <%= form.submit class: "btn btn-default" %>
  </div>

<% end %>

app/views/products/_inactive_product.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white border-2 border-red-500 rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flex-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <span class="px-2 py-1 text-xs font-semibold text-white bg-red-500 rounded-lg">Inactive</span>

        <h1 class="mt-4 text-3xl font-bold leading-none text-gray-800"><%= product.title %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= product.user.name ||=
      product.user.username %></p>
      </div>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= number_to_currency(product.current_donation_amount) %></p>
      <p class="text-sm text-gray-500">pledged of <%= number_to_currency(product.donation_goal) %></p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none">200</p>
      <p class="text-sm text-gray-500">backers</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none">Expired</p>
      <p class="text-sm text-gray-500"><%= time_ago_in_words(@product.expires_at) %> ago</p>
    </div>
  </div>

  <div class="flex flex-wrap items-start justify-between mb-6">
    <div class="w-full lg:w-3/5">
    <% if product.thumbnail.present? %>
      <%= image_tag product.thumbnail, class: "rounded" %>
    <% else %>
      <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
        <div class="">
          <p class="text-xs font-bold text-gray-600 uppercase">product</p>
          <h3 class="text-2xl text-black"><%= product.title %></h3>
        </div>
      </div>
    <% end %>
    </div>
    <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
      <p class="text-sm font-semibold text-gray-500 uppercase">Description</p>
      <%= product.description %>
    </div>
  </div>

  <div class="w-full lg:w-3/5">
    <%= render "comments/comments", commentable: product  %>
    <p>Comments are closed for inactive products</p>
  </div>

  <% if admin? || author_of(product) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_product_path(product), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delee', product_path(product), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="max-w-screen-md m-auto bg-black border border-gray-300 rounded-lg px-8 pt-6 pb-8">

  <h1 class="mb-6 text-3xl font-bold">Editing Product</h1>

  <%= render 'form', product: @product %>

</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="flex flex-wrap items-start justify-start">
  <% @products.each do |product| %>
    <div class="relative w-full bg-white p-6 border-2 border-blue-700 rounded-lg lg:w-1/4 lg:mr-8">
      <%= image_tag product.thumbnail.variant(resize_to_limit: [600, 400]), class: "rounded" if product.thumbnail.present? %>
      <h2 class="mb-2 text-2xl font-bold text-black">
        Title: <%= product.title %>
      </h2>
      <div class="text-black">
        Description: <%= truncate(strip_tags(product.description.to_s), length: 140) %>
      </div>
      <p class="text-black">
        Price: <%= product.price %>
      </p>
      <p class="text-sm opacity-75 text-black">
        Created by: <%= link_to product.user.name, user_path(product.user) %>
        <% # link_to cashflow_to_newebpay_path %>
      </p>
      <%= link_to 'View product', product, class: "btn btn-default inline-block text-center my-2 bg-blue" %>
      <!-- only if user login in or admin -->
      <% if author_of(product) %>
        <div class="absolute top-0 right-0 mt-2 mr-2">
          <%= link_to edit_product_path(product) do %>
            <svg class="w-6 h-6 text-black opacity-75 fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
              <title>edit</title>
              <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z">
              </path>
            </svg>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="max-w-screen-md m-auto bg-black border border-gray-300 rounded-lg px-20 pt-10">


  <h1 class="mb-6 text-4xl font-bold">Add Product</h1>

  <%= render 'form', product: @product %>

</div>

app/views/products/show.html.erb
<% if @product.active? %>
  <%= render "active_product", product: @product %>
<% else %>
  <%= render "inactive_product", product: @product %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, multipart: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="p-6 mb-5 text-red-500 bg-white rounded">
      <h2 class="font-bold text-red-500"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :thumbnail, "Project thumbnail", class: "label" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="mb-6">
    <%= form.label :donation_goal, class: "label" %>
    <%= form.text_field :donation_goal, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-default" %>
  </div>

<% end %>

app/views/projects/_inactive_project.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white border-2 border-red-500 rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flex-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <span class="px-2 py-1 text-xs font-semibold text-white bg-red-500 rounded-lg">Inactive</span>

        <h1 class="mt-4 text-3xl font-bold leading-none text-gray-800"><%= project.title %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= project.user.name ||=
      project.user.username %></p>
      </div>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= number_to_currency(project.current_donation_amount) %></p>
      <p class="text-sm text-gray-500">pledged of <%= number_to_currency(project.donation_goal) %></p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none">200</p>
      <p class="text-sm text-gray-500">backers</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none">Expired</p>
      <p class="text-sm text-gray-500"><%= time_ago_in_words(@project.expires_at) %> ago</p>
    </div>
  </div>

  <div class="flex flex-wrap items-start justify-between mb-6">
    <div class="w-full lg:w-3/5">
    <% if project.thumbnail.present? %>
      <%= image_tag project.thumbnail, class: "rounded" %>
    <% else %>
      <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
        <div class="">
          <p class="text-xs font-bold text-gray-600 uppercase">PROJECT</p>
          <h3 class="text-2xl text-black"><%= project.title %></h3>
        </div>
      </div>
    <% end %>
    </div>
    <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
      <p class="text-sm font-semibold text-gray-500 uppercase">Description</p>
      <%= project.description %>
    </div>
  </div>

  <div class="w-full lg:w-3/5">
    <%= render "comments/comments", commentable: project  %>
    <p>Comments are closed for inactive projects</p>
  </div>

  <% if admin? || author_of(project) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_project_path(project), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delee', project_path(project), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    Kickoff Tailwind
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 lg:px-10 pb-10">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to "Marketplace", root_path, class:"link text-4xl tracking-tight font-black" %>
    </div>
    <div>
      <%= link_to 'Add Product', new_product_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block bg-black" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
        <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <% if user_signed_in? %>
          <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block bg-black" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block bg-black" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/users/show.html.erb
<div>
  <%= @user.name %>
</div>
<div>
  <% if current_user == @user %>
    <p>you cannot follow yourself</p>
  <% elsif current_user.followees.include?(@user) %>
    <%= button_to "unfollow", unfollow_user_path(@user), method: :post, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block bg-black" %>
  <% else %>
    <%= button_to "follow", follow_user_path(@user), method: :post, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block bg-black" %>
  <% end %>
</div>